public class DataFile {

    String[] WordDef = {
            "vex", "to confuse or annoy",
            "abet", "to aid, help, encourage",
            "arid", "excessively dry",
            "balk", "to stop short and refuse to proceed",
            "bane", "a source of harm or ruin",
            "bard", "a poet, often a singer as well",
            "bias", "a tendency, inclination, prejudice",
            "bilk", "cheat, defraud",
            "boon", "a gift or blessing",
            "carp", "to complain, criticize, find fault",
            "coup", "a brilliant, unexpected act",
            "curt", "abrupt, short",
            "deft", "skillful, capable",
            "dour", "stern, joyless",
            "foil", "to thwart, frustrate, defeat",
            "goad", "to urge, spur, incite to action",
            "pert", "flippant, bold",
            "rail", "to scold, protest",
            "rash", "hasty, incautious",
            "raze", "to demolish, level",
            "rife", "abundant",
            "ruse", "a trick",
            "tome", "a large book",
            "wane", "to decrease in size, dwindle",
            "wily", "crafty, sly",
            "yoke", "to join, link",
            "annul", "to make void or invalid",
            "annex", "to incorporate territory or space",
            "abide", "to put up with",
            "abort", "to give up on an incomplete project or effort",
            "abase", "to humiliate, degrade",
            "abate", "to reduce, lessen",
            "abhor", "to hate, detest",
            "atone", "to repent, make amends",
            "allay", "to soothe, ease",
            "ardor", "extreme vigor, energy, enthusiasm",
            "aloof", "reserved, distant",
            "acute", "sharp, severe",
            "adept", "extremely skilled",
            "adorn", "to decorate",
            "aisle", "a passageway between rows of seats",
            "alias", "a false name or identity",
            "agile", "quick, nimble",
            "banal", "dull, commonplace",
            "belie", "to give a false impression of",
            "canny", "shrewd, careful",
            "chaos", "absolute disorder",
            "chide", "to voice disapproval",
            "covet", "to desire enviously",
            "decry", "to criticize openly",
            "defer", "to postpone something; to yield to another's wisdom",
            "deter", "to discourage, prevent from doing",
            "dirge", "a mournful song, especially for a funeral",
            "edict", "an order, decree",
            "elegy", "a speech given in honors of a dead person",
            "elude", "to evade, escape",
            "emend", "to correct or revise a written text",
            "emote", "to express emotion",
            "ennui", "boredom, weariness",
            "exalt", "to glorify, praise",
            "extol", "to praise, revere",
            "exult", "to rejoice",
            "feral", "wild, savage",
            "fetid", "having a foul odor",
            "flout", "to disregard or disobey openly",
            "forum", "a medium for lecture or discussion",
            "guile", "deceitful, cunning, sly behavior",
            "hardy", "robust, capable of surviving through adverse conditions",
            "inane", "silly and meaningless",
            "inept", "not suitable or capable, unqualified",
            "inure", "to cause someone or something to become accustomed to a situation",
            "knell", "the solemn sound of a bell, often indicating a death",
            "kudos", "praised for an achievement",
            "lithe", "graceful, flexible, supple",
            "lucid", "clear, easily understandable",
            "lurid", "ghastly, sensational",
            "maxim", "a common saying expressing a principle of conduct",
            "melee", "a confused struggle, a brawl",
            "mores", "the moral attitudes and fixed customs of a group of people",
            "nadir", "the lowest point of something",
            "pithy", "concisely meaningful",
            "quell", "to control or diffuse a potentially explosive situation",
            "revel", "to enjoy intensely",
            "salve", "a soothing balm",
            "staid", "sedate, serious, self-restrained",
            "stoic", "unaffected by passion or feeling",
            "tacit", "expressed without words",
            "toady", "one who flatters in the hope of gaining favors",
            "trite", "not original, overused",
            "usurp", "to seize by force, take possession of without right",
            "vapid", "lacking liveliness, dull",
            "wrath", "vengeful anger, punishment",
            "accede", "to agree",
            "abject", "wretched, pitiful",
            "abjure", "to reject, renounce",
            "abduct", "to kidnap, take by force",
            "aerial", "somehow related to the air",
            "aspire", "to long for, aim toward",
            "assail", "to attack",
            "assess", "to evaluate",
            "astute", "very clever, crafty",
            "asylum", "a place of refuge, protection, a sanctuary",
            "attain", "to achieve, arrive at",
            "avenge", "to seek revenge",
            "arable", "suitable for growing crops",
            "arcane", "obscure, secret, known only by a few",
            "allege", "to assert, usually without proof",
            "adhere", "to stick to something",
            "adroit", "skillful, dexterous",
            "acumen", "keen insight",
            "accord", "an agreement",
            "accost", "to confront verbally",
            "ballad", "a love song or narrative poem",
            "benign", "favorable, not threatening, mild",
            "berate", "to scold vehemently",
            "bereft", "devoid of, without",
            "blight", "a plague, disease",
            "brazen", "excessively bold, brash",
            "buffet", "to strike with force",
            "cajole", "to urge, coax",
            "candor", "honesty, frankness",
            "canvas", "a piece of cloth on which an artist paints",
            "caucus", "a meeting usually held by people working toward the same goal",
            "cavort", "to leap about, behave boisterously",
            "clamor", "loud noise",
            "cleave", "to divide into parts",
            "clergy", "members of Christian holy orders",
            "coerce", "to make somebody do something by force or threat",
            "cogent", "intellectually convincing",
            "covert", "secretly engaged in",
            "dearth", "a lack,  scarcity",
            "debase", "to lower the quality or esteem of something",
            "debunk", "to expose the falseness of something",
            "deface", "to ruin or injure something's appearance",
            "defile", "to make unclean, impure",
            "demean", "to lower the status or stature of something",
            "demure", "quiet, modest, reserved",
            "deride", "to laugh at mockingly, scorn",
            "despot", "one who has total power and rules brutally",
            "dispel", "to drive away, scatter",
            "dither", "to be indecisive",
            "divine", "godly, exceedingly wonderful",
            "docile", "easily taught or trained",
            "duress", "hardship, threat",
            "efface", "to wipe out, obliterate, run away",
            "elated", "overjoyed, thrilled",
            "elicit", "to bring forth, draw out, evoke",
            "enamor", "to fill with love, fascinate, usually used in passive form followed by of or with",
            "encore", "the audience's demand for a repeat performance; also the artist's performance; also the artist's performance in response to that demand",
            "enmity", "ill will, hatred, hostility",
            "entail", "to include as a necessary step",
            "eschew", "to shun, avoid",
            "evince", "to show, reveal",
            "exhort", "to urge, prod, spur",
            "extant", "existing, not destroyed or lost",
            "facade", "the wall of a building",
            "facile", "easy, requiring little effort",
            "fathom", "to understand, comprehend",
            "fecund", "fruitful, fertile",
            "fetter", "to chain, restrain",
            "fickle", "shifting in character",
            "florid", "flowery, ornate",
            "forage", "to graze, rummage for food",
            "foster", "to stimulate, promote, encourage",
            "frugal", "thrifty, economical",
            "garish", "gaudy, in bad taste",
            "genial", "friendly, affable",
            "hiatus", "a break or gap in duration or continuity",
            "impute", "to ascribe, to attribute blame",
            "induce", "to bring about, stimulate",
            "infamy", "notoriety, extreme ill-repute",
            "innate", "inborn, native, inherent",
            "jejune", "dull; immature; lacking in nutrition",
            "latent", "hidden, but capable of being exposed",
            "lavish", "given without limits",
            "limpid", "clear, transparent",
            "meager", "deficient in size or quality",
            "medley", "a mixture of differing things",
            "morass", "a wet swampy bog; figuratively, something that traps and confuses",
            "morose", "gloomy or sullen",
            "myriad", "consisting of a very great number",
            "novice", "a beginner, someone without training or experience",
            "nuance", "a slight variation in meaning, tone, expression",
            "obtuse", "lacking quickness of sensibility or intellect",
            "odious", "instilling hatred or intense displeasure",
            "ornate", "highly elaborate, excessively",
            "pallid", "lacking color",
            "pariah", "an outcast",
            "parody", "a satirical imitation",
            "patent", "readily seen or understood, clear",
            "pathos", "an emotion of sympathy",
            "placid", "calm, peaceful",
            "putrid", "rotten, foul",
            "quaint", "charmingly old-fashioned",
            "rancid", "having a terrible taste or smell",
            "rancor", "deep, bitter resentment",
            "rebuke", "to scold, criticize",
            "refute", "to prove wrong",
            "relish", "to enjoy",
            "remiss", "negligent, failing to take care",
            "renown", "honor, acclaim",
            "repose", "to rest, lie down",
            "revere", "to esteem, show deference, venerate",
            "revoke", "to take back",
            "ribald", "coarsely, crudely humorous",
            "serene", "calm, untroubled",
            "static", "stationary, fixed, unchanging, at rest",
            "stingy", "not generous, not inclined to spend or give",
            "stolid", "expressing little sensibility, unemotional",
            "tirade", "a long speech marked by harsh or bitting language",
            "torpid", "lethargic, dormant, lacking motion",
            "torrid", "giving off intense heat, passionate",
            "turgid", "swollen, excessively embellished in style or language",
            "utopia", "an imaginary and remote place of perfection",
            "vagary", "an unpredictable or erratic action, whim",
            "veneer", "a superficial or deceptively attractive appearance, facade",
            "vilify", "to lower in importance, defame",
            "wallow", "to pity oneself indolently; to become or remain helpless",
            "wanton", "undisciplined, lewd, lustful",
            "zenith", "the highest point, culminating point",
            "zephyr", "a gentle breeze",
            "anomaly", "something that does not fit into the normal order",
            "anguish", "extreme sadness, torment",
            "abstain", "to freely choose not to commit an action",
            "abridge", "to cut down, shorten",
            "abscond", "to sneak away and hide",
            "appease", "to calm, satisfy",
            "anxiety", "intense uneasiness",
            "artisan", "a craftsman",
            "ascetic", "practicing restraint as a means of self-discipline, usually religious",
            "ascribe", "to assign, credit, attribute to",
            "assuage", "to ease, pacify",
            "atrophy", "to wither away, decay",
            "audible", "able to be heard",
            "augment", "to add to, expand",
            "austere", "very bare, bleak",
            "avarice", "excessive greed",
            "aquatic", "relating to water",
            "arbiter", "one who can resolve a dispute, make a decision",
            "archaic", "of or relating to an earlier period in time, outdated",
            "amenity", "an item that increases comfort",
            "amiable", "friendly",
            "amorous", "showing love, particularly sexual",
            "adamant", "impervious, immovable, unyielding",
            "adverse", "antagonistic, unfavorable, dangerous",
            "acerbic", "biting, bitter in tone or taste",
            "acclaim", "high praise",
            "affront", "an insult",
            "affable", "friendly, amiable",
            "bashful", "shy, excessively timid",
            "battery", "assault, beating",
            "beguile", "to trick, deceive",
            "belated", "late, delayed",
            "beseech", "to beg, plead, implore",
            "blemish", "an imperfection, flaw",
            "burnish", "to polish, shine",
            "cadence", "a rhythm, progression of sound",
            "callous", "harsh, cold, unfeeling",
            "calumny", "an attempt to spoil someone else's reputation by spreading lies",
            "carouse", "to party, celebrate",
            "catalog", "to list, enter into a list",
            "caustic", "bitter, biting, acidic",
            "censure", "harsh criticism",
            "cherish", "to feel or show affection toward something",
            "cloying", "sickeningly sweet",
            "cobbler", "a person who makes or repairs shoes",
            "concede", "to accept as valid",
            "concise", "brief and direct in expression",
            "concoct", "to fabricate, make up",
            "concord", "harmonious agreement",
            "condone", "to pardon, deliberately overlook",
            "conduit", "a pipe or  channel through which something passes",
            "congeal", "to thicken into a solid",
            "connive", "to plot, scheme",
            "consign", "to give something over to another's care",
            "convene", "to call together",
            "copious", "profuse, abundant",
            "cordial", "warm, affectionate",
            "cunning", "sly, clever at being deceitful",
            "cursory", "brief to the point of being superficial",
            "curtail", "to lessen, reduce",
            "debacle", "a disastrous failure, disruption",
            "debauch", "to corrupt by means of sensual pleasures",
            "defunct", "no longer used or existing",
            "deplore", "to feel or express sorrow, disapprove",
            "devious", "not straightforward; deceitful",
            "dialect", "a variation of a language",
            "diffuse", "to scatter, thin out, break up",
            "disavow", "to deny knowledge of or responsibility for",
            "discern", "to perceive, detect",
            "disdain", "to scorn, hold in low esteem",
            "dissent", "to disagree",
            "distend", "to swell",
            "divulge", "to reveal something secret",
            "dormant", "sleeping, temporarily inactive",
            "dubious", "doubtful, of uncertain quality",
            "dynamic", "actively changing",
            "eminent", "distinguished, prominent, famous",
            "empathy", "sensitivity to another's feelings as if they were one's own",
            "emulate", "to imitate",
            "epitome", "a perfect example, embodiment",
            "erudite", "learned",
            "espouse", "to take up as a cause, support",
            "exigent", "urgent, critical",
            "expiate", "to make amends for, atone",
            "expunge", "to obliterate, eradicate",
            "fatuous", "silly, foolish",
            "fervent", "ardent, passionate",
            "flaccid", "limp, not firm or strong",
            "forlorn", "lonely, abandoned, hopeless",
            "forsake", "to give up, renounce",
            "fraught", "filled with or accompanied by",
            "furtive", "secretive, sly",
            "hapless", "unlucky",
            "haughty", "disdainfully proud",
            "heinous", "shockingly wicked, repugnant",
            "illicit", "forbidden, not permitted",
            "immerse", "to absorb, deeply involve, engross",
            "impinge", "to impact, affect, make an impression",
            "inhibit", "to prevent, restrain, stop",
            "insipid", "dull, boring",
            "insular", "separated and narrow-minded; tight-knit,  closed off",
            "laconic", "terse in speech or writing",
            "languid", "sluggish from fatigue or weakness",
            "larceny", "obtaining another's property by theft or trickery",
            "largess", "the generous giving of lavish gifts",
            "lenient", "demonstrating tolerance or gentleness",
            "mandate", "an authoritative command",
            "maudlin", "weakly sentimental",
            "mawkish", "characterized by sick sentimentality",
            "modicum", "a small amount of something",
            "mollify", "to soften in temper",
            "mundane", "concerned with the world rather than with heaven, commonplace",
            "mutable", "able to change",
            "nascent", "in the process of being born or coming into existence",
            "noisome", "unpleasant, offensive, especially to the sense of smell",
            "nomadic", "wandering from place to place",
            "nominal", "trifling, insignificant",
            "noxious", "harmful, unwholesome",
            "nurture", "to assist the development of",
            "oblique", "diverging from a straight line or course, not straightforward",
            "obscure", "unclear, partially hidden",
            "ominous", "foreboding or foreshadowing evil",
            "onerous", "burdensome",
            "opulent", "characterized",
            "oration", "a speech delivered in a formal or ceremonious manner",
            "pacific", "soothing",
            "palette", "a range of colors or qualities",
            "panacea", "a remedy for all ills or difficulties",
            "paradox", "an apparently contradictory statement that is perhaps true",
            "paragon", "a model of excellence or perfection",
            "paucity", "small in quantity",
            "perplex", "to confuse",
            "perusal", "a careful examination, review",
            "pillage", "to seize or plunder, especially in war",
            "placate", "to ease the anger of, soothe",
            "pliable", "flexible",
            "polemic", "an aggressive argument against a specific opinion",
            "portent", "an omen",
            "potable", "suitable for drinking",
            "presage", "an omen",
            "probity", "virtue, integrity",
            "procure", "to obtain, acquire",
            "profane", "lewd, indecent",
            "profuse", "plentiful, abundant",
            "prosaic", "plain, lacking liveliness",
            "protean", "able to change shape; multifaceted",
            "prowess", "extraordinary ability",
            "puerile", "juvenile, immature",
            "pungent", "having a pointed, sharp quality-often used to describe smells",
            "rapport", "mutual understanding and harmony",
            "raucous", "loud, boisterous",
            "refract", "to distort, change",
            "replete", "full, abundant",
            "reprove", "to scold, rebuke",
            "repulse", "to disgust",
            "rescind", "to take back, repeal",
            "resolve", "to find a solution",
            "respite", "a break, rest",
            "restive", "resistant, stubborn, impatient",
            "retract", "withdraw",
            "salient", "significant, conspicuous",
            "satiate", "to satisfy excessively",
            "seminal", "original, important, creating a field",
            "sensual", "involving sensory gratification, usually related to sex",
            "servile", "subservient",
            "sinuous", "lithe, serpentine",
            "soluble", "able to dissolve",
            "solvent", "a substance that can dissolve other substances",
            "stupefy", "to astonish, make insensible",
            "sublime", "lofty, grand, exalted",
            "surfeit", "an overabundant supply or indulgence",
            "surmise", "to infer with little evidence",
            "swarthy", "of dark color or complexion",
            "tedious", "dull, boring",
            "tenable", "able to be defended or maintained",
            "tenuous", "having little substance or strength",
            "umbrage", "resentment, offense",
            "uncanny", "of supernatural character or origin",
            "upbraid", "to criticize or scold severely",
            "vacuous", "lack of content or ideas, stupid",
            "verbose", "wordy, impaired by wordiness",
            "verdant", "green in tint or color",
            "vestige", "a mark or trace of something lost or vanished",
            "viscous", "not free-flowing; thick",
            "winsome", "charming, pleasing",
            "wistful", "full of yearning; musingly sad",
            "wizened", "dry, shrunken, wrinkled",
            "zealous", "fervent, filled with eagerness in pursuit of something",
            "animated", "lively",
            "abstruse", "hard to comprehend",
            "abrogate", "to abolish, usually by authority",
            "abdicate", "to give up a position, usually one of leadership",
            "advocate", "to argue in favor of something",
            "appraise", "to assess the worth or value of",
            "arrogate", "to take without justification",
            "artifact", "a remaining piece from an extinct culture or place",
            "atypical", "not typical, unusual",
            "aversion", "a particular dislike for something",
            "arboreal", "of or relating to trees",
            "allocate", "to distribute, set aside",
            "amenable", "willing, compliant",
            "amicable", "friendly",
            "anathema", "a cursed, detested person",
            "anecdote", "a short, humorous account",
            "admonish", "to caution, criticize, reprove",
            "acrimony", "bitterness, discord",
            "accolade", "high praise, special distinction",
            "alacrity", "eagerness, speed",
            "agnostic", "believing that the existence of God cannot be proven or disproven",
            "affluent", "rich, wealthy",
            "affinity", "a natural feeling of closeness",
            "behemoth", "something of tremendous power or size",
            "bequeath", "to pass on, give",
            "blandish", "to coax by using flattery",
            "buttress", "to support, hold up",
            "calamity", "an event with disastrous consequences",
            "catalyze", "to charge, inspire",
            "cerebral", "related to the intellect",
            "chastise", "to criticize severely",
            "clemency", "mercy",
            "coalesce", "to fuse into a whole",
            "coherent", "logically consistent, intelligible",
            "compound", "to combine parts",
            "compress", "to apply pressure, squeeze together",
            "confound", "to frustrate, confuse",
            "construe", "to interpret",
            "contrite", "penitent, eager to be forgiven",
            "criteria", "standards by which something is judged",
            "culpable", "deserving blame",
            "cupidity", "greed, strong desire",
            "daunting", "intimidating, causing one to lose courage",
            "decorous", "socially proper, appropriate",
            "delegate", "to hand over responsibility for something",
            "denounce", "to criticize publicly",
            "derelict", "abandoned, run-down",
            "desolate", "deserted, dreary, lifeless",
            "didactic", "intended to instruct",
            "diligent", "showing care in doing one's work",
            "disclose", "to reveal, make public",
            "dispatch", "to send off to accomplish a duty",
            "disperse", "to scatter, cause to scatter",
            "dissuade", "to persuade someone not to do something",
            "divisive", "causing dissent, discord",
            "dogmatic", "aggressively and arrogantly certain about unproved principles",
            "eclectic", "consisting of a diverse variety of elements",
            "ecstatic", "intensely and overpoweringly happy",
            "eloquent", "expressive, articulate, moving",
            "embezzle", "to steal money by falsifying records",
            "encumber", "to weigh down, burden",
            "enervate", "to weaken, exhaust",
            "engender", "to bring about, create, generate",
            "enthrall", "to charm, hold spellbound",
            "esoteric", "understood by only a select few",
            "ethereal", "heavenly, exceptionally delicate, refined",
            "euphoric", "elated, uplifted",
            "excavate", "to dig out of the ground and remove",
            "fidelity", "loyalty, devotion",
            "flagrant", "offensive, egregious",
            "frenetic", "frenzied, hectic, frantic",
            "gluttony", "overindulgence in food or drink",
            "gourmand", "someone fond of eating and drinking",
            "grievous", "injurious, hurtful; serious or grave in nature",
            "hallowed", "revered, consecrated",
            "harangue", "a lengthy, ranting speech",
            "hedonist", "one who believes pleasure should be the primary pursuit of humans",
            "hegemony", "domination over others",
            "implicit", "understood but not outwardly obvious, implied",
            "impudent", "casually rude, insolent, impertinent",
            "inchoate", "unformed or formless, in a beginning stage",
            "incisive", "clear, sharp, direct",
            "indigent", "very poor, impoverished",
            "indolent", "lazy",
            "infusion", "an injection of one substance into another; the permeation of one substance by another",
            "inimical", "hostile, enemy like",
            "iniquity", "wickedness or sin",
            "innovate", "to do something in an unprecedented way",
            "innuendo", "an insinuation",
            "insolent", "rude, arrogant, overbearing",
            "intrepid", "brave in the face of danger",
            "inundate", "to flood with abundance",
            "jubilant", "extremely joyful, happy",
            "linchpin", "something that holds separate parts together",
            "litigant", "someone engaged in a lawsuit",
            "luminous", "brightly shining",
            "manifest", "easily understandable, obvious",
            "manifold", "diverse, varied",
            "maverick", "an independent, nonconformist person",
            "mitigate", "to make less violent, alleviate",
            "moderate", "not extreme",
            "modulate", "to pass from one state to another, especially in music",
            "nebulous", "vaguely defined, cloudy",
            "neophyte", "someone who is young or inexperienced",
            "obdurate", "unyielding to persuasion or moral influences",
            "obsolete", "no longer used, out of date",
            "orthodox", "conventional, conforming to established protocol",
            "palliate", "to reduce the severity of",
            "paradigm", "an example that is a perfect pattern or model",
            "partisan", "a follower, adherent",
            "pellucid", "easily intelligible, clear",
            "penchant", "a tendency, partiality, preference",
            "penitent", "remorseful, regretful",
            "permeate", "to spread throughout, saturate",
            "pinnacle", "the highest point",
            "pittance", "a very small amount, especially relating to money",
            "plaudits", "enthusiastic approval, applause",
            "plethora", "an abundance, excess",
            "poignant", "deeply affecting, moving",
            "preclude", "to prevent",
            "pretense", "an appearance or action intended to deceive",
            "primeval", "original, ancient",
            "prudence", "cautious, circumspect",
            "prurient", "eliciting or possessing an extraordinary interest in sex",
            "punitive", "involving punishment",
            "quagmire", "a difficult situation",
            "quandary", "a perplexing unresolvable state",
            "quixotic", "idealistic, impractical",
            "relegate", "to assign to the proper place",
            "remedial", "intended to repair gaps in students' basic knowledge",
            "renovate", "restore, return to original state",
            "reprieve", "a temporary delay of punishment",
            "reproach", "to scold, disapprove",
            "resolute", "firm, determined",
            "ruminate", "to contemplate, reflect",
            "sagacity", "shrewdness, soundness of perspective",
            "sanguine", "optimistic, cheery",
            "scathing", "sharp, critical, hurtful",
            "sensuous", "involving sensory gratification",
            "sobriety", "sedate, calm",
            "spurious", "false but designed to seem plausible",
            "stagnate", "to become or remain inactive, not develop, not flow",
            "strident", "harsh, loud",
            "succinct", "marked by compact precision",
            "taciturn", "not inclined to talk",
            "temerity", "audacity, recklessness",
            "timorous", "timid, fearful",
            "tortuous", "winding",
            "tranquil", "calm",
            "travesty", "a grossly inferior imitation",
            "truncate", "to shorten by cutting off",
            "unctuous", "smooth or greasy in texture, appearance, or manner",
            "undulate", "to move in waves",
            "validate", "to confirm, support, corroborate",
            "venerate", "to regard with respect; to honor",
            "veracity", "truthfulness, accuracy",
            "vigilant", "watchful, alert",
            "virtuoso", "one who excels in an art; a highly skilled musical performer",
            "vocation", "the work in which someone is employed, profession",
            "anonymous", "being unknown, unrecognized",
            "apprehend", "to seize, arrest",
            "aesthetic", "artistic, related to the appreciation of beauty",
            "appalling", "inspiring shock, horror, disgust",
            "apathetic", "lacking concern, emotion",
            "antipathy", "a strong dislike, repugnance",
            "anthology", "a selected collection of writings, songs, etc.",
            "ascertain", "to perceive, learn",
            "aspersion", "a curse, expression of ill-will",
            "assiduous", "hard-working, diligent",
            "attribute", "to credit, assign",
            "audacious", "excessively bold",
            "arbitrary", "based on factors that appear random",
            "alleviate", "to relieve, make more bearable",
            "ambiguous", "uncertain, variably interpretable",
            "amorphous", "without definite shape or type",
            "analgesic", "something that reduces pain",
            "analogous", "similar to, so that an analogy can be drawn",
            "anarchist", "one who wants to eliminate all government",
            "adulation", "extreme praise",
            "adumbrate", "to sketch out in a vague way",
            "acquiesce", "to agree without protesting",
            "accretion", "slow growth in size or amount",
            "aggrieved", "distressed, wronged, injured",
            "aggregate", "a whole or total",
            "bellicose", "prone to aggression and conflict",
            "bombastic", "excessively confident, pompous, overblown",
            "bourgeois", "a middle-class person, capitalist",
            "cacophony", "tremendous noise, disharmonious sound",
            "calibrate", "to set, standardize",
            "capacious", "very spacious",
            "captivate", "to get the attention of, hold",
            "chronicle", "a written history",
            "coagulate", "to thicken, clot",
            "cognizant", "aware, mindful",
            "collusion", "secret agreement, conspiracy",
            "colossus", "a gigantic statue or thing",
            "compliant", "ready to adapt oneself to another's wishes",
            "complicit", "being an accomplice in a wrongful act",
            "confidant", "a person entrusted with secrets",
            "congenial", "pleasantly agreeable",
            "congruity", "the quality of being in agreement",
            "consonant", "in harmony",
            "constrain", "to forcibly restrict",
            "contusion", "bruise",
            "conundrum", "puzzle, problem",
            "convivial", "characterized by feasting, drinking, merriment",
            "corrosive", "having the tendency to erode or eat away",
            "credulity", "readiness to believe",
            "crescendo", "a steady increase in intensity or volume",
            "cultivate", "to nurture, improve, refine",
            "delineate", "to describe, outline, shed light on",
            "demagogue", "a leader who appeals to a people's prejudices",
            "denigrate", "to belittle, diminish the opinion of",
            "depravity", "wickedness",
            "deprecate", "to belittle, depreciate",
            "desecrate", "to violate the sacredness of a thing or place",
            "destitute", "impoverished, utterly lacking",
            "diffident", "shy, quiet, modest",
            "dilatory", "tending to delay, causing delay",
            "discomfit", "to thwart, baffle",
            "disparage", "to criticize or speak ill of",
            "disparate", "sharply differing, containing sharply contrasting elements",
            "disrepute", "a state of being held in low regard",
            "dissemble", "to conceal, fake",
            "dissipate", "to disappear, cause to disappear",
            "duplicity", "crafty dishonesty",
            "ebullient", "extremely lively, enthusiastic",
            "effulgent", "radiant, splendorous",
            "egregious", "extremely bad",
            "elaborate", "complex, detailed, intricate",
            "elucidate", "to clarify, explain",
            "emaciated", "very thin",
            "embellish", "to decorate, adorn",
            "emollient", "soothing",
            "empirical", "base on observation or experience",
            "enigmatic", "mystifying, cryptic",
            "equivocal", "ambiguous, uncertain, undecided, dubious",
            "etymology", "the history of words, their origin and development",
            "exculpate", "to free from guilt or blame, exonerate, vindicate",
            "excursion", "a trip or outing, usually for fun",
            "execrable", "loathsome, detestable",
            "exonerate", "to free from guilt or blame, exculpate, vindicate",
            "expedient", "advisable, advantageous, serving one's self-interest",
            "expurgate", "to remove offensive or incorrect parts, usually of a book",
            "extricate", "to disentangle, free from difficulty",
            "fabricate", "to make up, invent",
            "forestall", "to prevent, thwart, delay",
            "fortitude", "strength, guts",
            "fractious", "troublesome or irritable",
            "frivolous", "of little importance, trifling",
            "garrulous", "talkative, wordy",
            "grandiose", "on a magnificent or exaggerated scale",
            "hackneyed", "unoriginal, trite",
            "harrowing", "greatly distressing, vexing",
            "hierarchy", "a system with ranked groups, usually according to social, economic, or professional class",
            "hypocrisy", "pretending to believe what one does not",
            "immutable", "not changeable",
            "impassive", "stoic, not susceptible to suffering",
            "imperious", "commanding, domineering",
            "impetuous", "rash; hastily done",
            "implement", "an instrument, utensil, tool",
            "implicate", "to involve in an incriminating way, incriminate",
            "incarnate", "to give human form to",
            "incessant", "unending",
            "increment", "an enlargement; the process of increasing",
            "incumbent", "one who holds an office",
            "ineffable", "unspeakable, incapable of being expressed through words",
            "ingenious", "clever, resourceful",
            "ingenuous", "not devious; innocent and candid",
            "innocuous", "harmless, inoffensive",
            "inoculate", "to introduce a microorganism, serum, or vaccine into an organism in order to increase immunity to illness; to vaccinate",
            "insidious", "appealing but imperceptibly harmful, seductive",
            "insinuate", "to suggest indirectly or subtly",
            "instigate", "to urge, goad",
            "insurgent", "one who rebels",
            "integral", "necessary for completeness",
            "interject", "to insert between other things",
            "invective", "an angry verbal attack",
            "irascible", "easily angered",
            "judicious", "having or exercising sound judgment",
            "laudatory", "expressing admiration or praise",
            "lethargic", "in a state of sluggishness or apathy",
            "liability", "something for which one is legally responsible, usually involving a disadvantage or risk",
            "maelstrom", "a destructive whirlpool that rapidly sucks in objects",
            "malleable", "capable of being shaped or transformed",
            "mercurial", "characterized by rapid change or temperamentally",
            "nefarious", "villainous",
            "negligent", "habitually careless, neglectful",
            "nocturnal", "relating to or occurring during the night",
            "notorious", "widely and unfavorably known",
            "obfuscate", "to render incomprehensible, to confuse, to darken or dim",
            "oblivious", "lacking consciousness or awareness of something",
            "obstinate", "not yielding easily, stubborn",
            "officious", "offering one's services when they are neither wanted nor needed",
            "oscillate", "to sway from one side to the other",
            "ostracism", "exclusion from a group",
            "palatable", "agreeable to the taste",
            "paramount", "greatest in importance, rank, or character",
            "parsimony", "frugality, stinginess",
            "pathology", "a deviation from the normal",
            "penurious", "miserly, stingy",
            "pervasive", "having the tendency to spread throughout",
            "petulance", "rudeness, irritability",
            "platitude", "an uninspired remark, cliche",
            "plausible", "believable, reasonable",
            "plenitude", "an abundance",
            "potentate", "one who has great power, a ruler",
            "pragmatic", "practical",
            "precipice", "the face of a cliff, a steep or overhanging place",
            "prescient", "to have foreknowledge of events",
            "prescribe", "to lay down a rule",
            "privation", "lacking basic necessities",
            "propagate", "to multiply, spread out",
            "propriety", "the quality or state of being proper, decent",
            "proscribe", "to condemn, outlaw",
            "querulous", "whiny, complaining",
            "quotidian", "daily",
            "reclusive", "solitary, shunning society",
            "reconcile", "to return to harmony",
            "rectitude", "uprightness, extreme morality",
            "refurbish", "to restore, clean up",
            "repentant", "penitent, sorry",
            "repudiate", "to reject, refuse to accept",
            "reputable", "of good reputation",
            "reservoir", "reserves, large supply",
            "resilient", "able to recover from misfortune; able to withstand adversity",
            "sedentary", "sitting, settled",
            "semaphore", "a visual signal",
            "somnolent", "sleepy, drowsy",
            "sovereign", "having absolute authority in a certain realm",
            "strenuous", "requiring tremendous energy or stamina",
            "subjugate", "to bring under control, subdue",
            "surrogate", "one acting in place of another",
            "sycophant", "one who flatters for self-gain",
            "tractable", "easily controlled",
            "transient", "passing through briefly; passing into and out of existence",
            "transmute", "to change or alter in form",
            "tremulous", "fearful",
            "trenchant", "effective, articulate, clear-cut",
            "truculent", "ready to fight, cruel",
            "turpitude", "depravity, moral corruption",
            "vacillate", "to fluctuate, hesitate",
            "venerable", "deserving of respect because of age or achievement",
            "vicarious", "experiencing through another",
            "vindicate", "to avenge; to free from allegation; to set free",
            "vitriolic", "having a caustic quality",
            "vivacious", "lively, sprightly",
            "whimsical", "fanciful, full of whims",
            "antecedent", "something that came before",
            "antagonism", "hostility",
            "accessible", "obtainable, reachable",
            "accentuate", "to stress, highlight",
            "absolution", "freedom from blame, guilt, sin",
            "abnegation", "denial of comfort to oneself",
            "aberration", "something that differs from the norm",
            "apocryphal", "fictitious, false, wrong",
            "antithesis", "the absolute opposite",
            "antiseptic", "clean, sterile",
            "antiquated", "old, outdated",
            "auspicious", "favorable, indicative of good things",
            "archetypal", "the most representative or typical example of something",
            "ameliorate", "to improve",
            "ambivalent", "having opposing feelings",
            "amalgamate", "to bring together, unite",
            "anesthesia", "loss of sensation",
            "aggrandize", "to increase or make greater",
            "benefactor", "a donor, one who gives money or grifts",
            "benevolent", "marked by goodness or doing good",
            "boisterous", "loud and full of energy",
            "capitulate", "to surrender",
            "capricious", "subject to whim, fickle",
            "circuitous", "roundabout",
            "circumvent", "to get around",
            "collateral", "secondary or supporting",
            "colloquial", "characteristic of informal conversation",
            "combustion", "the act or process of burning",
            "commodious", "roomy",
            "compelling", "forceful, demanding attention",
            "compensate", "to make an appropriate payment fro something",
            "complement", "to complete, make perfect",
            "compliment", "an expression of esteem or approval",
            "condolence", "an expression of sympathy in sorrow",
            "confection", "a sweet, fancy food",
            "confluence", "a gathering together",
            "conformist", "one who behaves the same as others",
            "consecrate", "to dedicate something to a holy purpose",
            "consummate", "to complete",
            "contravene", "to contradict, oppose, violate",
            "convention", "an assembly of people",
            "convoluted", "intricate, complicated, involved",
            "coronation", "the act of crowning",
            "corpulence", "extreme fatness",
            "counteract", "to neutralize, make ineffective",
            "cumulative", "increasing, building upon itself",
            "defamatory", "harmful toward another's reputation",
            "deliberate", "intentional, reflecting careful consideration",
            "derivative", "taken directly from a source, unoriginal",
            "desiccated", "dried up, dehydrated",
            "despondent", "feeling depressed, discouraged, hopeless",
            "diaphanous", "light, airy, transparent",
            "diminutive", "small or miniature",
            "discordant", "not agreeing, not in harmony with",
            "discretion", "the quality of being reserved in speech or action; good judgment",
            "discursive", "rambling, lacking order",
            "dissonance", "lack of harmony or consistency",
            "effrontery", "impudence, nerve, insolence",
            "ephemeral", "short-lived, fleeting",
            "epistolary", "relating to or contained in letters",
            "equanimity", "composure",
            "evanescent", "fleeting, momentary",
            "exacerbate", "to make more violent, intense",
            "exasperate", "to irritate, irk",
            "exorbitant", "excessive",
            "extraneous", "irrelevant, extra, not necessary",
            "fallacious", "incorrect, misleading",
            "fastidious", "meticulous, demanding, having high and often unattainable standards",
            "felicitous", "well suited, apt",
            "figurative", "symbolic",
            "fortuitous", "happening by chance, often lucky or fortunate",
            "gratuitous", "uncalled for, unwarranted",
            "gregarious", "drawn to the company of others, sociable",
            "iconoclast", "one who attacks common beliefs or institutions",
            "idolatrous", "excessively worshipping one object or person",
            "impeccable", "exemplary, flawless",
            "imperative", "necessary, pressing",
            "impervious", "impenetrable, incapable of being affected",
            "implacable", "incapable of being appeased or mitigated",
            "incendiary", "inflammatory, causing combustion",
            "indigenous", "originating in a region",
            "inexorable", "incapable of being persuaded or placated",
            "injunction", "an order of official warning",
            "inquisitor", "one who inquires, especially in a hostile manner",
            "insatiable", "incapable of being satisfied",
            "intimation", "an indirect suggestion",
            "inveterate", "stubbornly established by habit",
            "inviolable", "secure from assault",
            "iridescent", "showing rainbow colors",
            "laceration", "a cut, tear",
            "licentious", "displaying a lack of moral or legal restraint",
            "malevolent", "wishing harm to befall others",
            "mendacious", "having a lying, false character",
            "meticulous", "extremely careful with details",
            "nonchalant", "having a lack of concern, indifference",
            "obsequious", "excessively compliant or submissive",
            "ostensible", "appearing as such, seemingly",
            "pejorative", "derogatory, uncomplimentary",
            "perfidious", "disloyal, unfaithful",
            "pernicious", "extremely destructive or harmful",
            "phlegmatic", "uninterested, unresponsive",
            "precocious", "advanced, developing ahead of time",
            "proclivity", "a strong inclination toward something",
            "profligate", "dissolute, extravagant",
            "promulgate", "to proclaim, make known",
            "propensity", "an inclination, preference",
            "propitious", "favorable",
            "pugnacious", "quarrelsome, combative",
            "rhapsodize", "to engage in excessive enthusiasm",
            "saccharine", "sickeningly sweet",
            "sacrosanct", "holy, something that should not be criticized",
            "salutation", "a greeting",
            "scrupulous", "painstaking, careful",
            "scurrilous", "vulgar, coarse",
            "solicitous", "concerned, attentive",
            "sophomoric", "immature, uninformed",
            "submissive", "easily yielding to authority",
            "tangential", "incidental, peripheral, divergent",
            "tantamount", "equivalent in value or significance",
            "temperance", "moderation in action or thought",
            "transgress", "to violate, go over a limit",
            "ubiquitous", "existing everywhere, widespread",
            "variegated", "diversified, distinctly marked",
            "vehemently", "marked by intense force or emotion",
            "vindictive", "vengeful",
            "vituperate", "to berate",
            "vociferous", "loud, boisterous",
            "approbation", "praise",
            "appropriate", "to take, make use of",
            "arbitration", "the process or act of resolving a dispute",
            "altercation", "a dispute, fight",
            "agriculture", "farming",
            "camaraderie", "brotherhood, jovial unity",
            "circumspect", "cautious",
            "clairvoyant", "able to perceive things that normal people cannot",
            "clandestine", "secret",
            "complacency", "self-satisfied ignorance of danger",
            "compunction", "distress caused by feeling guilty",
            "concomitant", "accompanying in a subordinate fashion",
            "consolation", "an act of comforting",
            "conspicuous", "obvious, noticeable, attracting attention",
            "constituent", "an essential part",
            "consumption", "the act of consuming",
            "contentious", "having a tendency to quarrel or dispute",
            "corroborate", "to support with evidence",
            "culmination", "the climax toward which something progresses",
            "deferential", "showing respect for another's authority",
            "deleterious", "harmful",
            "demarcation", "the marking of boundaries or categories",
            "disaffected", "rebellious, resentful of authority",
            "discrepancy", "difference, failure of things to correspond",
            "disgruntled", "upset, not content",
            "disseminate", "to spread widely",
            "efficacious", "effective",
            "enfranchise", "to grant the vote to",
            "forbearance", "patience, restraint, tolerance",
            "ignominious", "humiliating, disgracing",
            "impecunious", "poor",
            "impertinent", "rude, insolent",
            "impregnable", "resistant to capture or penetration",
            "inclination", "a tendency, propensity",
            "indignation", "anger sparked by something unjust or unfair",
            "indomitable", "not capable of being conquered",
            "intractable", "difficult to manipulate, unmanageable",
            "irreverence", "disrespect",
            "irrevocable", "incapable of being taken back",
            "legerdemain", "deception, sleight-of-hand",
            "libertarian", "advocating principles of liberty and free will",
            "magnanimous", "noble, generous",
            "malediction", "a curse",
            "meritorious", "worthy of esteem or reward",
            "munificence", "generosity in giving",
            "nondescript", "lacking a distinctive character",
            "penultimate", "next to last",
            "perfunctory", "showing little interest or enthusiasm",
            "pulchritude", "physical beauty",
            "punctilious", "eager to follow rules or conventions",
            "reciprocate", "to give in return",
            "redoubtable", "formidable",
            "regurgitate", "to vomit",
            "requisition", "a demand for goods, usually made by an authority",
            "resplendent", "shiny, glowing",
            "restitution", "restoration to the rightful owner",
            "serendipity", "luck, finding good things without looking for them",
            "solipsistic", "believing that oneself is all that exists",
            "speculative", "not based in fact",
            "superfluous", "exceeding what is necessary",
            "terrestrial", "relating to the land",
            "trepidation", "fear, apprehension",
            "utilitarian", "relating to or aiming at usefulness",
            "vicissitude", "event that occurs by chance",
            "antediluvian", "ancient",
            "choreography", "the arrangement of dances",
            "commendation", "a notice of approval or recognition",
            "commensurate", "corresponding in size or amount",
            "conciliatory", "friendly, agreeable",
            "congregation", "a gathering of people, especially for religious services",
            "cosmopolitan", "sophisticated, worldly",
            "disheartened", "feeling a loss of spirit or morale",
            "effervescent", "bubbly, lively",
            "hypothetical", "supposed or assumed true, but unproven",
            "inarticulate", "incapable of expressing oneself clearly through speech",
            "incorrigible", "incapable of correction, delinquent",
            "inextricable", "hopelessly tangled; entangled",
            "interlocutor", "someone who participates in a dialogue or conversation",
            "interminable", "without possibility of end",
            "intransigent", "refusing to compromise, often on an extreme opinion",
            "multifarious", "having great diversity or variety",
            "obstreperous", "noisy, unruly",
            "ostentatious", "excessively showy, glitzy",
            "perspicacity", "shrewdness, perceptiveness",
            "pertinacious", "stubbornly persistent",
            "predilection", "a preference or inclination for something",
            "presumptuous", "disrespectfully bold",
            "recalcitrant", "defiant, unapologetic",
            "recapitulate", "to sum up, repeat",
            "renunciation", "to reject, especially by public announcement",
            "anachronistic", "being out of correct chronological order",
            "accommodating", "helpful, obliging, polite",
            "chronological", "arranged in order of time",
            "circumscribed", "marked off, bounded",
            "comprehensive", "including everything",
            "conflagration", "great fire",
            "flabbergasted", "astounded",
            "heterogeneous", "varied, diverse in character",
            "idiosyncratic", "peculiar to one person; highly individualized",
            "indefatigable", "incapable of defeat, failure,  decay",
            "juxtaposition", "the act of placing two things next to each other for implicit comparison",
            "metamorphosis", "the change of form, shape, substance",
            "philanthropic", "charitable, giving",
            "preponderance", "superiority in importance of quantity",
            "prepossessing", "occupying the mind to the exclusion of other thoughts or feelings",
            "reprehensible", "deserving rebuke",
            "sanctimonious", "giving a hypocritical appearance of piety",
            "scintillating", "sparkling",
            "surreptitious", "stealthy",
            "circumlocution", "indirect and wordy language",
            "grandiloquence", "lofty, pompous language",
            "contemporaneous", "existing during the same time",
            "incontrovertible", "not able to be denied or disputed",
            "hypogeal", "underground,subterranean",
            "rapprochement", "an establishment or reestablishment of harmonious relations.",
            "cruciverbalist", "a designer or aficionado of crossword puzzles."
    };

    String[] ChineseWordDef = {
        "一", "one", "一月", "January", "女", "women", "女孩", "girl", "女性", "female", "人", "human being, person.", "女人", "women, female",
        "二", "two", "二月", "Feburary", "三", "three", "三十", "thirty", "三十一", "thirty-one", "十", "ten", "十一", "eleven", "十二", "twelve",
        "二十", "twenty", "二十一", "twenty-one", "三十", "thirty", "口", "to surround", "田", "field;a family name.", "田地", "field;land",
        "农田", "farmland", "力", "strength", "人力", "manpower,labor power", "力气", "strength", "男", "male", "男人", "man,male",
        "男女", "men and women", "乙", "twist", "乙醇", "alcohol", "艺", "skill;art", "艺术", "art", "园艺", "the art of gardening", "藝", "art",
        "亿", "a hundred million", "十亿", "one billion", "億", "billion", "忆", "heart", "记忆", "memory", "回忆录", "memoirs", "憶", "Remember",
        "也", "also", "也许", "perhaps;maybe", "她", "she,her", "她们", "they;them(feminine)", "他", "he,him", "他们", "they;them(masculine/ or feminine)",
        "门", "gate", "大门", "The door", "门卫", "entrance guard;doorkeeper", "門", "door", "们", "we are", "她们", "they,them(feminine)",
        "他们", "they,them(masculine/ or feminine)", "手", "hand", "手指", "finger", "手套", "gloves", "戈", "lance", "戈壁", "desert", "我", "me",
        "我们", "we,us", "寻找", "to look for", "找到", "to find", "宀", "roof", "士", "earth", "土人", "an aborigine", "人士", "notable person",
        "女士", "polite address women", "小孩", "children", "小妹", "younger sister", "尔", "you,your;-ly,-like;that", "偶尔", "sometimes;on occasion",
        "你", "you", "你们", "you(plural)", "你好", "how are you?", "匕", "ladle", "匕首", "dagger", "它们", "they,them(not human beings)", "了", "change status",
        "好了", "finished", "懂了", "understood", "了解", "to understand", "子", "child", "儿子", "son", "孩子", "child", "好", "be well", "好人", "good person",
        "厶", "be private", "纟", "silk", "累", "silk farming", "好累", "be very tired", "艮", "be tough", "很", "very", "很好", "very good", "口", "mouth",
        "人口", "population", "口子", "hole,opening,cut,rip", "三口人", "three people", "马", "horse;a family name", "小马", "pony", "马力", "housepower",
        "吗", "it sentence to question", "言", "words", "语言", "language", "文言", "classical Chinese", "誰", "who?whom?", "大", "big", "大哥", "elder brother",
        "大学", "university", "大夫", "medical doctor", "夫", "husband", "夫人", "Mrs.,Madam", "马夫人", "Mrs. Ma, Madam Ma", "天", "heaven,God,day,natural",
        "天天", "every day", "天子", "the emperor", "气", "breath,vapor,soul,energy", "空气", "air", "气球", "ballon", "竹", "bamboo", "竹马", "stick toy horse",
        "青梅竹马", "couple met from childhood", "笑", "smile,to laugh at", "好笑", "being funny", "笑星", "star comedian", "儿", "child", "儿子", "son",
        "儿女", "daughter", "无", "not have,to lack", "无人", "unmanned;depopulated", "无力", "lack strength,feel weak", "无大无小", "regardless of size,not knowing status", "辛", "bitter,toilsome,eighth", "辛苦", "hard,painstaking", "幸运", "lucky", "幸福", "happiness", "王", "family name king",
        "国王", "king", "玉", "jade", "玉手", "beautiful hand", "主", "lord;host", "主人", "landlord;master", "主力", "main force(team,army,factory shift,etc)",
        "住", "to live,to stay,to stop;verb-ending", "住所", "residence", "住址", "address", "注", "note", "注意", "pay attention to", "注射", "injection",
        "驻", "to stop;be stationary at;posted to", "驻军", "station troops", "木", "tree;be dull,stiff", "土木", "building and construction",
        "木讷", "honest and slow witted", "禾", "grain;rice", "禾苗", "seedlings of cereal", "矢", "arrow", "失", "lose,fail;defeated", "丢失", "lost",
        "失身", "to lose one's virginity", "矮", "be short", "矮子", "short person,dwarf", "矮小", "diminutive", "亡", "to flee;to hide;be gone",
        "死亡", "death,to die", "忙", "be busy", "心", "heart", "小心", "be careful!", "无心", "not feel like it;unintentionally", "您", "you(denote supperior)",
        "元", "first;Japanese yen", "远", "be far away", "远大", "be long-range", "跳远", "the long-jump", "云", "to say", "云彩", "cloud", "远", "to transport;fate,luck",
        "运气", "luck", "霉气", "bad luck", "院", "public building", "院子", "courtyard", "医院", "hospital", "园", "garden", "公园", "park", "园丁", "gardener,teacher",
        "不", "negative prefix verb", "不好", "No Good!", "不很", "not very...", "很不", "very un-...", "不忙", "There's no hurry", "太", "extremely", "太忙", "be too busy",
        "太太", "married lady, wife", "田太太", "Mrs.Tian", "太子", "prince,crown prince", "高", "be tall;to tower", "高大", "be big and tall", "高中", "high school",
        "高矮", "height", "搞", "to do,to make;to get", "搞鬼", "tricks", "搞好", "do well", "搞笑", "funny", "又", "again", "又不", "not at all...",
        "又高又大", "be both tall and big", "又矮又小", "be both short and small", "敲", "to blackmail;to swindle", "敲打", "beat", "稿", "stalk;draft,sketch",
        "稿子", "manuscript;plan", "月", "moon,month", "月亮", "moon", "月份", "month", "膏", "ointment;fat;be oily", "膏药", "adhesive plaster", "药膏", "ointment",
        "可", "can;to suit;certainly", "可笑", "be laughable", "可口", "to taste good", "不可", "should not", "可心", "be satisfying", "可可", "cocoa",
        "可口可乐", "Coca Cola", "阿门", "amen(prayer)", "啊", "sentence particle !", "好累啊", "I'm really tired!", "小心啊", "Be careful!", "曰", "say",
        "子曰", "Confucious said", "书", "book;letter;document;to write", "手书", "personal letter.", "天书", "illegible writing", "情书", "love letter",
        "报", "report;newspaper", "小报", "tabloid", "报纸", "newspaper", "毛", "mildew;gross;a measuer for dimes", "毛发", "hair", "毛巾", "towel",
        "笔", "brush;writing instrument", "毛笔", "writing brush", "笔心", "pencil-lead;pen re-fill", "玩", "a play", "玩笑", "a joke", "古玩", "antique",
        "钅", "gold,metal", "山", "mountain", "山口", "mountain pass", "爬山", "mountain climbing", "冈", "ridge", "山冈", "low hill",
        "钢", "to sharpen;steel", "钢笔", "pen", "炼钢", "steelmaking", "刚", "be hard;only;exactly", "刚才", "just now", "刚刚", "be exactly",
        "刚好", "Perfect", "岗", "sentry;ridge;mound or hill", "岗位", "post", "站岗", "stand gaurd", "纲", "essential principle;discipline authority",
        "纲要", "outline", "纲目", "detailed outline", "八", "eight", "王八", "cuckold(vulgar)", "鸡巴", "dick(vulgar)", "铅", "lead", "铅笔", "pencil",
        "米", "rice (orgin)", "大米", "rice", "米饭", "cooked rice", "迷", "develope passion for;fan", "迷路", "to get lost", "迷宫", "labyrinth",
        "谜", "riddle(orgin)", "谜语", "riddle", "谜底", "answer of a riddle", "目", "eye(orgin)", "书目", "booklist,catalog of books",
        "目中无人", "be supercilious,haughty", "眯", "get into person eye;take nap", "眯缝", "narrow one's eye", "刀", "knife(orgin)", "刀子", "knife",
        "刀口", "knife edge;incision;crucial point", "日本刀", "katana,dagger,knife", "分", "componet;a share,a fraction", "分手", "to part with somebody",
        "分心", "to distract somebody", "份", "a measure for portions", "份额", "share;portion", "粉", "dust,powder,rice noodle",
        "粉笔", "chalk", "粉末", "powder", "纷", "be tangle;confusing;be profuse", "纷纷", "one after another;be numerous and confused",
        "纠纷", "dispute", "吩", "to give somebody an order", "盼", "to hope for;to look", "盼望", "look forward to", "皿", "dish",
        "器皿", "containers and untensils", "盆", "pot,basin,container", "盆子", "basin", "贝", "a cowrie(orginal)", "贝壳", "shell",
        "贝克汉姆", "Beckham", "贫", "be poor,insufficient", "贫穷", "poor", "贫民", "poor people;pauper", "扮", "to act;make a face",
        "装扮", "dress up", "扮演", "play the role", "氛", "atmosphere", "气氛", "ambience", "立", "to stand", "独立", "independent",
        "中立", "neutral", "立刻", "right away", "里", "a unit of distance", "里边", "inside", "故里", "hometown", "理", "principle;reason",
        "理解", "understand", "理论", "theory", "厘", "smallest part", "厘米", "centimeter", "哩", "as often", "啫哩", "jelly", "童", "child;children(orgin)",
        "童女", "maiden virgin", "童心", "childlike innocence of an old man", "童话", "fairy tale", "中", "middle;fit perfectly",
        "中心", "center core", "中立", "neutrality", "中国", "China", "钟", "clock(orgin)", "十分钟", "ten minutes", "一见钟情", "love at first sight",
        "衣", "gown", "毛衣", "sweater", "大衣", "overcoat", "表", "to show; be on surface", "手表", "wristwatch", "国", "nation", "国王", "king",
        "中立国", "neutral nation", "美国", "USA", "羊", "sheep(orgin)", "小羊", "lamb", "山羊", "mountain goat", "美", "beautiful",
        "美好", "be fine,happy,glorious", "夕", "dusk", "夕阳", "setting sun", "卜", "divine", "外", "outside; relatives mother or sister",
        "外国", "foreign country", "外表", "surface,appearance", "看", "to look at;to look after", "看中", "to select,choose", "看门", "doorkeeper",
        "西", "west", "西边", "west side", "西瓜", "watermelon", "西餐", "Western-style food", "贵", "be expensive,precious",
        "可贵", "be valuable,deserve commendation", "贵人", "government VIP", "更", "still more;to change", "更好", "be better;even more",
        "更快更高更强", "Faster,Higher,Stronger", "便", "be convenient", "小便", "to piss,a piss", "大便", "to shit", "便衣", "street clothes",
        "且", "further", "且慢", "wait a moment", "祖", "grandfather,ancestor(orgin)", "祖国", "fatherland", "祖父", "grandfather",
        "租", "to rent;lease", "租房", "tenement", "租户", "tenant", "组", "such as section or department", "组织", "organize,organization",
        "组员", "member", "粗", "be coarse", "粗心", "be careless", "粗人", "rough or unclouth person", "阻", "to obstruct", "阻力", "resistance",
        "宜", "be appropriate", "便宜", "be inexpensive", "宜人", "pleasant,delightful", "要", "to want,to ask for", "要人", "important person",
        "要不", "otherwise, or else,or", "要好", "be on good terms,be friends", "头", "the head", "木头", "wood;a fool", "买", "a buy",
        "买方", "buyer", "买进", "to buy;purchase", "卖", "to sell", "买卖", "business", "卖国", "be a traitor", "日", "sun", "日子", "day,date;period of time",
        "日元", "Japanese yen", "日报", "daily newspaper", "老", "be old", "老二", "second son or daughter", "老人", "old person",
        "老小", "young and old", "老太太", "old lady,my ma", "老头儿", "old coot", "老头子", "old fart", "者", "suffix verb a person who...",
        "老者", "an old guy or guys", "作者", "author", "犭", "cruetly,courage,ferocity", "猪", "pig", "猪排", "pork chop", "猪肉", "pork",
        "煮", "cook up,to boil", "煮器", "boiler", "煮饭", "cook rice,cook a meal", "者", "to spread out,to display,be displayed;to author",
        "著者", "writer,author", "名著", "masterpiece", "暑", "summer(orgin)", "暑假", "summer vacation", "暑热", "summer heat",
        "绪", "end of thread;clue;to be together", "绪论", "introduction", "堵", "to stop up;to stifle", "堵塞", "stop up", "堵车", "traffic jam",
        "署", "a government office;to arrange piece work", "署名", "signature", "都", "metropolis,capital", "都是", "all", "首都", "capital",
        "都市", "city", "廿", "twenty", "甘", "to taste sweet", "甘甜", "sweet,luscious", "或", "perhaps;or", "匹", "mate;one half of a pair",
        "一匹马", "a horse,one horse", "匹夫", "ordinary man;stupid fellow", "国家兴亡,匹夫有责", "Rise and fall of a nation rest with every one of its citizens",
        "四", "four", "四书", "four book or core classics confucianism", "五", "five", "五十", "fifty", "十五", "fifteen", "六", "six", "七", "seven",
        "九", "nine", "人", "to enter", "入口", "entrance", "入手", "put your hand in,get started,make a beginning", "什", "first syllable what?",
        "什锦", "assorted", "么", "second syllable what?", "什么", "what?", "桌", "some object made of wood", "桌子", "wood table",
        "书桌", "wooden writing desk", "奇", "be weird", "好奇", "be curious,be intrested in oddities", "好奇心", "curiosity(state of mind)",
        "椅", "chair", "椅子", "wooden chair", "摇椅", "rocking chair", "东", "east", "东边", "east side", "东家", "host", "钱", "money(orgin)",
        "九分钱", "9 cents", "金钱", "money", "有钱人", "rich man", "浅", "be shallow;be mild", "深浅", "depth", "浅色", "light-color", "个", "be individual",
        "个人", "each person;oneself", "个子", "stature", "个儿", "each one", "all of'em", "文", "pattern;language", "中文", "Chinese Language",
        "文言", "classical chinese", "这", "this", "这个", "this one", "这么", "so,thus,in this case", "这里", "here", "这儿", "there",
        "那", "that(opposite to\"this\")", "那个", "that,that one", "那么", "that being so,in that case;to that extent", "那里", "there",
        "那儿", "there", "金", "gold,metal(orgin)", "五金", "gold,silver,cooper,iron, and tin", "合", "to join,to bring together",
        "合金", "alloy", "组合", "to form;combination", "给", "to give;to allow;for,to supply", "给我书", "gives me books",
        "给我看", "let me look", "给我买", "buys for me", "给予", "to render", "有", "to have;there is,there are", "有力", "be energetic,strong",
        "有钱", "be rich", "有口无心", "speak sharply but with out malice", "干", "shield;have to do with;be dry;be empty;main part;to do",
        "干吗", "What shall we do?", "汗", "sweat", "汗毛", "fine body-hair", "汗衫", "T-shirt", "肝", "the liver", "肝脏", "liver",
        "心肝", "my darling,baby, sweetie", "杆", "a measure for rifles,pistols,and spears", "杆子", "pole", "杆秤", "steelyard", "走", "to walk",
        "她走了", "She's left,she's gone.", "赶", "to rush after;to chase off", "赶工", "try to get the work done faster", "赶快", "Hurry,come on!",
        "厂", "factory", "厂房", "factory building;workshop", "工厂", "factory", "岸", "high cliff,high riverbank", "岸标", "shore beacon",
        "旱", "drought;dry land", "旱田", "dry farmland", "旱季", "dry season", "刊", "to carve,to publish,publications to engrave",
        "刊物", "publication", "刊登", "to publish", "没", "inundate;negates and other verbs", "没有", "there isn't,there aren't;doesn't have;hasn't",
        "没买", "hasn't bought", "没什么", "it doesn't matter;never mind", "身", "torso", "可身", "to fit well", "合身", "to fit well", "身分", "position,rank",
        "有身子", "being pregnant", "寸", "thumb;inch", "尺寸", "measurement;size", "分寸", "sense of propriety", "射", "to shoot", "射门", "to shoot(at the goal,in sports)",
        "射手", "marks man,sharpshooter", "谢", "thanks;excuse oneself(orgin)", "谢谢", "Thank you", "不谢", "You're welcome", "凋谢", "to wither",
        "吉", "lucky(orgin)", "吉日", "lucky day", "吉他", "guitar", "桔", "tangerine", "桔汁", "orange juice", "桔子", "mandarin orange",
        "结", "to tie together;knot;to bear fruit", "结合", "to unite,to combine;to be married", "结婚", "to marry", "喜", "to enjoy;give enjoyment",
        "喜人", "be satisfying", "喜好", "to like,to love,be fond of", "欠", "yawn;to owe,to lack", "欠钱", "owe money,be in debt",
        "哈欠", "yawn", "欢", "be pleased", "喜欢", "to like", "欢喜", "be joyful;be fond of", "欢笑", "laugh delightedly", "止", "to stop",
        "阻止", "to prevent,obstruct", "不止三个", "not stopping at three,not only three", "闲人止步", "No entering!", "足", "foot;be sufficient.",
        "十足", "sheer,total,absolute,utter", "不足", "insufficient", "跟", "heel;to follow,to go with;with", "跟班", "attendant", "青", "be green or blue",
        "青菜", "green vegetables", "青草", "green grass", "请", "to invite;please...", "谁请", "Who's paying?", "请勿吸烟", "No Smoking", "情", "emotion;circumstances",
        "情报", "information;intelligence", "情人", "sweetheart,mistress,secret lover", "清", "be clear;to clear", "清楚", "be clear,distinct",
        "清高", "aloof from politics and material pursuits", "晴", "clear sky", "晴天", "a fine day", "睛", "the pupil of the eye", "眼睛", "eye",
        "问", "to ask(for information)", "问住", "to stump with a question", "请问", "Would you please tell me...", "耳", "ear", "耳目", "hearsay;spy,informer",
        "木耳", "edible tree fungus", "石耳", "edible rock lichen", "闻", "to hear,to smell", "闻人", "a famous person", "耳闻", "to hear about,especially superficially",
        "闲", "leisure", "闲心", "leisure mood", "闲", "to chat;gossip", "间", "space;be separated from;to separate", "中间", "between,amog;the middle,center",
        "田间", "farm,field", "人间", "world of human affairs", "间谍", "spy", "另", "separately", "另外", "in addition", "别", "to separete,to part;Don't...!",
        "别人", "other people", "分别", "to part;sort out,differentiate;difference", "个别", "specific;very few;be exceptional", "别买", "Don't buy it!",
        "朋", "friend", "朋友", "friend", "猪朋狗友", "bad companions", "友", "friend", "友谊", "friendship", "父", "father(orgin)", "祖父", "grandfather",
        "父老", "elders(as in a district)", "教父", "god-father", "毋", "don't", "毋庸", "need not", "见", "to see,to perceive", "远见", "foresight;vision",
        "见解", "opinion,view", "亲", "relatives;to hold dear;in person;relatives by marriage", "父亲", "father", "六亲", "the six relatives: father,mother,elder brothers,wife,children",
        "母(orgin)", "mother", "母亲", "mother", "父母", "parents;mother and father", "母乳", "breast milk", "哥", "elder brother", "哥哥", "older brother",
        "大哥", "oldest brother;used to address politely older brother", "表哥", "older male cousin", "弓", "bow;to bend or arch", "弓子", "bow",
        "弓箭", "bow and arrow", "弟", "younger brother(orgin)", "弟弟", "younger male cousin,younger brother", "二弟", "second younger brother", "小弟", "kid brother",
        "弟子", "disciple,pupil", "姐", "older sister", "小姐", "Miss(use with care!)", "大姐", "oldest sister;used to address politely a woman", "未", "not yet",
        "未可", "cannot,be unable to", "未来", "the future", "妹", "younger sister", "姐妹", "sisters", "妹夫", "brother-in-law", "表妹", "younger female cousin",
        "氏", "clan", "田王氏", "Tián Wáng shì Mrs. Tian", "纸", "paper", "报纸", "newspaper", "手纸", "toilet paper", "长", "be long;to grow;be senior",
        "长大", "to grow up", "长子", "eldest son", "长度", "length", "张", "to open out,to open up", "张弓", "draw a bow", "三张纸", "sheets of paper", "画", "to paint,a painting",
        "画报", "illustrated magazine", "国画", "traditional Chinese painting", "一张画", "a painting", "臼", "mortar", "臼齿", "molar tooth", "白", "be white(orgin)",
        "白天", "in the daytime", "白白", "vainly,to no purpose", "白给", "to give free of charge", "白人", "white guy,white girl", "表白", "to confess", "勺", "to wrap",
        "勺", "spoon;frying pan", "勺子", "spoon", "木勺", "wooden ladle", "的", "a suffix to nouns and pronouns", "我的", "my, mine", "有的", "some", "目的", "aim,purpose",
        "好的", "OK! All good!", "包", "to wrap", "包子", "steamed filled dumpling", "书包", "book-bag,satchel", "面包", "bread", "跑", "to run,a race", "跑马", "a horse-race;ride a horse",
        "一百米跑", "the 100m race", "抱", "to hold in your arms,to hug;to cherish", "拥抱", "to hug", "胞", "be related by blood;afterbirth,placenta", "胞弟", "younger blood brother",
        "胞衣", "afterbirth", "细胞", "cell(biology)", "衤", "gown", "袍", "long gown or robe", "长袍", "long gown", "浴袍", "pajamas", "泡", "to soak;to pester;be together;bubble;blister;light",
        "泡沫", "foam", "泡泡", "bubble", "饱", "to be full,to have had enough to eat", "吃饱了", "I'm full;I have enough.", "还没吃饱", "I'm not full yet.", "火", "fire",
        "火力", "firepower", "火山", "volcano", "肝火", "be hot-tempered", "炮", "cannon,artillery;a shot from a gun", "炮弹", "shell(bullet,artillery)", "炮火", "artillery fire",
        "己", "self", "己方", "our side", "已", "already;to end,to cease", "已经", "already", "纪", "write down;record;year;discipline", "年纪", "age", "世纪", "century",
        "纪要", "summary;minutes of a meeting,etc.", "记", "to remember;to record;mark,sign", "记者", "reporter", "记住", "to fix in the mind;to remember",
        "巴", "open hand;palm;to stick to;to hope for", "巴结", "curry favor with;fawn on", "巴士", "bus", "吧", "a sentence-final particle;indicates supposition",
        "好吧", "Okay!Fine!", "走吧", "Let's go!", "把", "to grasp;a handful;to guard;a particle used to bring object and verb", "一把米", "a handful of rice",
        "一把勺", "a spoon", "爸", "papa,father", "爪", "claws", "爪牙", "claws and teeth,minion", "爪子", "claw", "爬", "to crawl,to creep;to climb", "爬行", "to creep",
        "爬行动物", "reptile", "本", "root;volume(book);capital(money)", "日本", "Japan", "本人", "I,myself;in person", "本钱", "capital(money)", "一本书", "a book,one book",
        "以人为本", "people-oriented", "对", "to face;facing;to match;be correct", "对了", "That's right!", "对手", "adversary,opponent", "对钟", "to set a clock",
        "兄", "older brother", "兄弟", "brothers", "胞兄", "表兄", "older male cousin on the mother's side", "兑", "to hand over", "兑给", "to pay to", "外币兑换", "foreign currency exchange",
        "税", "tax", "租税", "land tax", "报税", "to make a customs declaration,to declare goods on which duty is owed", "悦", "to speak;try to persuade;be happy delighted",
        "说笑", "to talk and laugh together", "说一不二", "to mean what you say", "古", "be ancient(orgin)", "古老", "be ancient,be age-old", "古玩", "antique,curio",
        "故", "be ancient;to die;cause;intentionally", "故土", "one's native land", "故人", "dead person(respectable)", "估", "to appraise,to estimate", "估产", "estimate the harvest/yield",
        "估价", "to appraise,evaluate", "固", "be firm,sold,resolutely;orginally,in the first place;a conjunction word", "固定", "to fix,fixed", "固体", "solid body",
        "苦", "be bitter", "吃苦", "to suffer,to endure hardship", "甘苦", "'the sweet and the bitter,'weal and woe", "枯", "dried wood;be withered,be dried out",
        "枯萎", "withered,to wither", "辜", "guilt;a crime(orgin)", "辜负", "to let down", "无辜", "innocent", "重", "be heavy;do over again,to repeat by mistake",
        "重要", "be important", "贵重", "be valuable", "重了", "be done twice,get repeated", "太重了", "too heavy!", "买重了", "has/have bought an extra one(one too many)",
        "董", "to correct,to supervise(orgin)", "古董", "an antique;an old duffer", "董事", "a director;a trustee", "懂", "to understand", "看不懂", "be unable to understand",
        "看懂了", "be able to understand", "是", "to be,am,is,are;be right", "可是", "but", "要是", "if;if only", "不是", "\"No!\";a fault", "是的", "Yes!;That's right!",
        "先", "to precede;late(deceased)", "先父", "my late father", "先夫", "my late husband", "先天", "innate,inborn", "生", "to bear(give birth to)", "先生", "Mr.;teacher",
        "生日", "birthday", "生长", "to grow;grow up,be brought up", "生人", "a stranger", "女生", "female student", "生手", "green horn;be new to something", "李", "plum tree",
        "李子", "plum", "李先生", "Mr.Li", "亥", "the twelfth", "the period of the day from 9 p.m. to 11 p.m.", "孩", "child", "孩童", "children", "孩子", "child",
        "小孩儿", "(colloquial)child", "嗽", "cough", "咳嗽", "cough,to cough", "学", "to study,to learn", "学生", "student", "大学", "university", "学问", "learning,scholarship",
        "姓", "surname;to be surnamed...", "姓氏", "surname", "您贵姓", "What is your name?(polite)", "我姓李", "My(sur)name is Li", "名", "name", "姓名", "full name",
        "有名", "be famous", "字", "written character", "名字", "name(given name)", "字母", "alphabet;leter", "别字", "mispronounced or wrongly written character",
        "汉字", "Chinese characters", "叫", "to call;to be called;to order a person to do something", "马叫", "the horse neighs", "叫苦", "to complain,whine",
        "叫什么", "What's it called(named)?", "叫花子", "(colloquial)beggar", "牛", "cow", "牛奶", "milk", "牛排", "steak", "告", "to inform", "报告", "to report;a report",
        "告别", "to leave,to part or depart from;to say goodbye to", "斥", "to scold", "斥骂", "to reproach", "诉", "to inform,to sue", "告诉", "to inform,to file a lawsuit;to make a legal complaint against", "诉说", "to tell,to relate", "知", "to know", "知心", "to understand each other", "先知", "a person having foresight;prophet,soothsayer",
        "首", "chief;the head", "首都", "capital city", "首先", "be the first;in the first place,above all", "首要", "be very important", "首长", "senior officer",
        "道", "road;to say;the Way", "道谢", "to thank", "道喜", "to congratulate", "道士", "Taoist(Daoist)priest", "道学", "neo-Confucian", "道理", "reason,logical basis;doctrine",
        "知道", "to know", "此", "this", "此外", "furthermore,in addition", "些", "few", "大些", "be a bit larger", "好些", "quite a few", "这一些书", "this lot of books",
        "些许", "a few", "位", "position,standpoint;seat;a polite measure for persons", "位子", "seat", "学位", "academic degree", "三位小姐", "three young ladies",
        "三位先生", "three gentlemen", "支", "branch;to prop up;to draw(money)", "干支", "stems and branches", "枝", "a measure for pens,pencils,pieces of chalk,etc.",
        "树枝", "tree branch", "一枝笔", "a pen", "技", "skill;expertise or specialised training", "技术", "technology;skills", "杂技", "acrobatics,circus", "千", "a thousand",
        "千古", "be eternal,of the ages", "千里", "many miles;a long journey", "千里马", "a superb horse,a horse that can run many miles", "千里之行始于足下",
        "a thousand-mile journey begins with the first step", "央", "center", "中央", "center,central", "英", "be bold;flower(bookish)", "英国", "England",
        "英里", "English mile", "黑", "black", "黑心", "an evil mind", "黑白不分", "cannot distinguish between right and wrong", "黑人", "black man",
        "占", "to divine;seize;constitute", "占卜", "divination,to divine", "占据", "to occupy", "站", "stand,to stand", "站长", "stationmaster",
        "火车站", "train station", "汽车站", "bus station", "粘", "to paste,to glue;be sticky", "粘贴", "affix;stick", "粘糊", "sticky", "战", "war(orgin)",
        "战士", "soldier", "战友", "comrade-in-arms", "沾", "to moisten;to receive benefits;to be infected by", "沾边", "touch on only lightly,to be relevant",
        "广", "be broad", "广大", "be vast,huge", "广东", "Canton,Guangdong", "店", "store;inn", "书店", "bookstore", "夜店", "night club",
        "钻", "to drill;to go into,go through;to study intensely;to bore", "钻石", "diamond", "电钻", "an electric drill;a power drill",
        "贴", "to paste something on;stay close to;to pay;allowance", "粘贴", "stick on,paste", "点", "dot,drop;to drip;a bit;feature;to light",
        "点心", "snack,pastry,dim sum", "要点", "要点", "main points,essential point or points", "三点六", "3.6", "雨", "rain(orgin)", "雨点", "raindrops",
        "雨衣", "raincoat", "雷雨", "thunderstorm", "今", "to command;to make,to cause;a command", "令兄", "(respectful)your older brother",
        "一令纸", "a ream of paper", "零", "zero;tiny bit", "零点", "zero point;zero hour", "零食", "snacks", "页", "head;leaf,page",
        "页码", "page number", "领", "to lead;neck,collar;main point", "领土", "territory", "领先", "to be in the lead,to lead", "领子", "collar", "要领", "main points",
        "铃", "a small bell", "门铃", "doorbell", "齿", "teeth", "牙齿", "tooth,teeth", "唇亡齿寒", "The teeth are cold when the lips", "龄", "age,years;length of time,duration",
        "高龄", "be advanced in years", "妙龄", "tender age of a young girl", "邻", "to pity", "怜爱", "to love tenderly", "可怜", "pitiable", "半", "half",
        "一大半", "majority", "三点半", "half past three", "另一半", "多", "be numerous", "多么好", "How very good!", "多半", "the greater part;for the most part,probably",
        "多谢", "Many thanks!", "好多了", "Much better!", "多多益善", "the more the better", "少", "be few;be young"
    };
}